baseURL = 'https://tyrantrey.github.io/SWGuide'
title = 'Soulworker 靈魂行者退坑指南'
theme = "reimu"
languageCode = 'zh-TW'
defaultContentLanguage = 'zh-TW'
[languages]
[languages.zh-TW]
languageName = '繁體中文'
weight = 1
hasCJKLanguage = true
ignoreFiles = [
    "content/.obsidian/*",
    "D:/Code/SWGuide/content/post/Template/Template.md",
    "D:/Code/SWGuide/content/post/Template/_index.md",
    "D:/Code/SWGuide/content/post/Template/temp.md",
    "D:/Code/SWGuide/content/post/Template/toc.md",
    "D:/Code/SWGuide/content/post/Template/副本.md",
    "D:/Code/SWGuide/content/post/Template/裝備.md",
    "D:/Code/SWGuide/content/post/Template/",
]
